version: '3'

services:
  client:
    build:
      context: client
      dockerfile: ../.docker/dev/client.dev.Dockerfile
    volumes:
      - ./client:/app
    ports:
      - 3000:80
    depends_on:
      - dashboard
    networks:
      - neura-launch-network
    restart: on-failure

  dashboard:
    build:
      context: ./dashboard
      dockerfile: ../.docker/dev/dashboard.dev.Dockerfile
    volumes:
      - ./dashboard:/app
    ports:
      - 8080:8080
    depends_on:
      - database
    networks:
      - neura-launch-network
    restart: on-failure

  builder:
    build:
      context: ./builder
      dockerfile: ../.docker/dev/builder.dev.Dockerfile
    volumes:
      - ./builder:/app
    ports:
      - 6969:6969
    networks:
      - neura-launch-network
    restart: on-failure

  database:
    image: postgres
    container_name: postgres_database
    env_file: dashboard/.env
    ports:
      - 5432:5432
    networks:
      - neura-launch-network

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin_container
    env_file: dashboard/.env
    depends_on:
      - database
    ports:
      - 5050:80
    networks:
      - neura-launch-network
    restart: unless-stopped

networks:
  neura-launch-network:
    driver: bridge